### ISSUE TITLE
Is this support Google Login.

### ISSUE THREAD

**Issue by RailgunWinjoy** [lorensr/apollo-accounts#6]
I found this package on the Meteor Forum and haven't tried yet.
I'm migrating my Vue-Meteor web app to Apollo-Nuxt and i have to do something with the Account-system.

Do you plan to implement the Google,Facebook auth ? Or can you simply describing how to do it

**Comment by lorensr** [comment]
I haven't done OAuth, but this library supports it: https://www.accountsjs.com/
